### PR TITLE
Convert unit tests into JUnit4 format

### PR DESCRIPTION
**Pull request by ahitrin**
Motivation for using JUnit4:

1. It's more modern test format, and should be known better for developers nowadays.
2. Its annotations are already used in some tests.

### CODE REVIEW

**Review by bpkroth — COMMENTED** [review]
I don't have strong opinions about this, but roughly looks good to me.

@timveil do you want to take a look?  I think you did something similar a while back for one of the other tests.

**Comment by Berkof** [comment]
@timveil pls check this PR

**Comment by ahitrin** [comment]
Hello, @timveil 
Could you please take a look at this proposal? Could it be useful or not?

**Review by apavlo — APPROVED** [review]
LGTM

**Comment by ahitrin** [comment]
Thank you, folks!

**Pull request merged**
